export { authRouter } from './auth'
export { healthRouter } from './health'
export { userRouter } from './user'
export { createRouter } from './create'
export { consultRouter } from './consult'
export { updateRouter } from './update'
